// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKrwRU3MwpNkiWsaj1I4m4f5D2dd8vEB4',
    appId: '1:371640890792:android:6cd39e95a79d03e6e4d99d',
    messagingSenderId: '371640890792',
    projectId: 'my-whatsapp-backend',
    storageBucket: 'my-whatsapp-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD3gtgeQdpXEhvVSJzHE8Ggmm7H9__giI',
    appId: '1:371640890792:ios:2802df0ac979fa0fe4d99d',
    messagingSenderId: '371640890792',
    projectId: 'my-whatsapp-backend',
    storageBucket: 'my-whatsapp-backend.appspot.com',
    androidClientId: '371640890792-hs7aots37t2ljig4a89cr18hvtr8n5pa.apps.googleusercontent.com',
    iosClientId: '371640890792-g3nd3h8l7lai4bnp4skq3u525ep5lkc4.apps.googleusercontent.com',
    iosBundleId: 'com.nguyentruongphong.whatsappUi',
  );
}
